version: '3.6'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
    container_name: elasticsearch
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
    - docker-elk
    ports:
    - 9200:9200
    - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.3
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    networks:
    - docker-elk
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch

networks:
  docker-elk:
    driver: bridge